(()=>{
if(window.__MT_MANUAL_V1)return;window.__MT_MANUAL_V1=true;
const HIDDEN=8,H5=7,origRender=render,origGraphs=graphs,origReport=report,origSettings=settings,origRows=rows;
const active=()=>S.machines.filter(m=>m.id!==HIDDEN);
rows=function(){return origRows().filter(r=>r.machineId!==HIDDEN)};
function withActive(fn){return function(...args){const all=S.machines;if(S.selected===HIDDEN)S.selected=7;S.machines=active();try{return fn.apply(this,args)}finally{S.machines=all}}}
render=withActive(origRender);graphs=withActive(origGraphs);report=withActive(origReport);settings=withActive(origSettings);
function hhmm(v){if(typeof v!=='string')return null;const m=v.trim().replace(/\s+/g,'').match(/^(\d+):([0-5]\d)$/);return m?Number(m[1])+Number(m[2])/60:null}
function dec(v){if(typeof v!=='string')return null;const x=v.trim().replace(/,/g,'');if(!/^\d+(?:\.\d+)?$/.test(x))return null;const n=Number(x);return Number.isFinite(n)?n:null}
function fmt(n){return Number.isFinite(n)?n.toFixed(3):'—'}
function entryFields(m){if(m.type==='haas')return `<label>Cycle Time — HH:MM</label><input id="cycle" type="text" inputmode="numeric" placeholder="123:30"><label>Feed Time — HH:MM</label><input id="feed" type="text" inputmode="numeric" placeholder="88:15">`;if(m.id===H5)return `<label>Machine Hour Meter — HH:MM</label><input id="machine" type="text" inputmode="numeric" placeholder="123:30"><label>Spindle Time — HH:MM</label><input id="spindle" type="text" inputmode="numeric" placeholder="75:45">`;return `<label>Machine Time — decimal hours</label><input id="machine" type="text" inputmode="decimal" placeholder="123.5">`}
function enterTimes(){const m=S.machines.find(x=>x.id===S.selected);if(S.readings.some(x=>x.machineId===m.id&&x.date===today())&&!confirm('A reading already exists today. Replace it?'))return;verifyInfo.textContent=m.type==='haas'||m.id===H5?'Enter the cumulative values exactly as HH:MM. They are converted to decimal hours when saved.':'Enter the cumulative decimal-hour value exactly as shown on the machine.';verifyFields.innerHTML=entryFields(m);preview.classList.add('hidden');pending={photo:null};verifyModal.style.display='flex';ocrMsg.textContent=m.id===H5?'Machine Hour Meter and Spindle Time are logged separately. Your first Spindle Time entry becomes the starting spindle baseline because that metric was added after your production baseline was set.':m.type==='haas'?'Cycle Time and Feed Time are logged separately.':'Manual decimal-hour entry.'}
scan=enterTimes;
function saveManual(){const m=S.machines.find(x=>x.id===S.selected),b=base(m.id);if(!b)return alert('Set the baseline first.');let v;if(m.type==='haas'){const c=hhmm(cycle.value),f=hhmm(feed.value);if(c===null||f===null)return alert('Use HH:MM for both Haas values, for example 123:30.');v={cycle:c,feed:f}}else if(m.id===H5){const mh=hhmm(machine.value),sp=hhmm(spindle.value);if(mh===null||sp===null)return alert('Use HH:MM for both Hurco 5 values, for example 123:30.');v={machine:mh,spindle:sp}}else{const mh=dec(machine.value);if(mh===null)return alert('Enter decimal hours, for example 123.5.');v={machine:mh}}
const old=S.readings.find(x=>x.machineId===m.id&&x.date===today()),prior=reads(m.id).filter(x=>!old||x.id!==old.id).at(-1),pc=prior?prior.cumulative:null;let daily;if(m.type==='haas')daily={cycle:v.cycle-(pc?pc.cycle:b.cycle),feed:v.feed-(pc?pc.feed:b.feed)};else if(m.id===H5){if(!Number.isFinite(b.spindle)){if(!confirm('Spindle Time was not part of your original baseline. Use this first spindle value as the spindle baseline? Today’s spindle daily total will start at 0.'))return;b.spindle=v.spindle;b.spindleSetAt=new Date().toISOString()}daily={machine:v.machine-(pc?pc.machine:b.machine),spindle:v.spindle-(pc&&Number.isFinite(pc.spindle)?pc.spindle:b.spindle)}}else daily={machine:v.machine-(pc?pc.machine:b.machine)};
if(Object.values(daily).some(x=>!Number.isFinite(x)||x<0))return alert('New cumulative value is lower than the previous value/baseline.');if(m.type==='haas'&&daily.feed>daily.cycle+.01&&!confirm('Feed Time is greater than Cycle Time. Save anyway?'))return;S.readings=S.readings.filter(x=>!(x.machineId===m.id&&x.date===today()));S.readings.push({id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),machineId:m.id,date:today(),cumulative:v,daily,source:'manual',photo:null,createdAt:new Date().toISOString()});save();closeVerify();render()}
saveReading=saveManual;
function patchDashboard(){document.querySelectorAll('button').forEach(b=>{if(b.textContent.includes('Scan Machine'))b.textContent='✎ Enter Times';else if(/^📷?\s*Scan$/.test(b.textContent.trim()))b.textContent='✎ Enter Times'});const m=S.machines.find(x=>x.id===S.selected);if(!m)return;if(m.id===H5){const cards=[...app.querySelectorAll('.card')],detail=cards.find(c=>c.querySelector('h2')?.textContent===m.name);if(detail&&!detail.querySelector('.h5-extra')){const tr=S.readings.find(x=>x.machineId===H5&&x.date===today()),note=document.createElement('div');note.className='notice good h5-extra';note.style.marginTop='8px';note.innerHTML=tr&&Number.isFinite(tr.daily.spindle)?`<b>Spindle Time today:</b> ${tr.daily.spindle.toFixed(2)} h`:'<b>Hurco 5:</b> enter Machine Hour Meter and Spindle Time in HH:MM.';detail.appendChild(note)}}}
const r0=render;render=function(){const out=r0();patchDashboard();return out};render();
history=function(){const m=S.machines.find(x=>x.id===S.selected),r=reads(m.id).reverse();app.innerHTML=`<div class="card"><button class="secondary" onclick="render()">← Dashboard</button><h1>Time History — ${m.name}</h1>${r.length?`<div style="overflow:auto"><table><thead><tr><th>Date</th><th>Captured Data</th><th>Daily Total</th><th>Source</th></tr></thead><tbody>${r.map(x=>`<tr><td>${x.date}</td><td>${m.type==='haas'?`<div style="text-align:left"><b>Cycle Time:</b> ${fmt(x.cumulative.cycle)}</div><div style="text-align:left"><b>Feed Time:</b> ${fmt(x.cumulative.feed)}</div>`:m.id===H5?`<div style="text-align:left"><b>Machine Hour Meter:</b> ${fmt(x.cumulative.machine)}</div><div style="text-align:left"><b>Spindle Time:</b> ${fmt(x.cumulative.spindle)}</div>`:`<div style="text-align:left"><b>Machine Time:</b> ${fmt(x.cumulative.machine)}</div>`}</td><td>${m.type==='haas'?`<div style="text-align:left"><b>Cycle:</b> ${fmt(x.daily.cycle)} h</div><div style="text-align:left"><b>Feed:</b> ${fmt(x.daily.feed)} h</div>`:m.id===H5?`<div style="text-align:left"><b>Machine:</b> ${fmt(x.daily.machine)} h</div><div style="text-align:left"><b>Spindle:</b> ${fmt(x.daily.spindle)} h</div>`:`${fmt(x.daily.machine)} h`}</td><td>${x.source}</td></tr>`).join('')}</tbody></table></div>`:`<div class="notice">No readings yet.</div>`}</div>`}
function reportRows(){return rows().map(x=>({x,m:S.machines.find(q=>q.id===x.machineId)}))}
csv=function(){let s='Date,Machine,Type,Cumulative Machine/Cycle,Cumulative Feed,Cumulative Spindle,Daily Machine/Cycle,Daily Feed,Daily Spindle,Source\n';reportRows().forEach(({x,m})=>s+=`${x.date},"${m.name}",${m.type},${m.type==='haas'?x.cumulative.cycle:x.cumulative.machine},${m.type==='haas'?x.cumulative.feed:''},${m.id===H5&&Number.isFinite(x.cumulative.spindle)?x.cumulative.spindle:''},${m.type==='haas'?x.daily.cycle:x.daily.machine},${m.type==='haas'?x.daily.feed:''},${m.id===H5&&Number.isFinite(x.daily.spindle)?x.daily.spindle:''},${x.source}\n`);dl('Machine-Track.csv',s,'text/csv')}
xls=function(){let s='MACHINE TRACK REPORT\n\nDate\tMachine\tType\tCumulative Machine/Cycle\tCumulative Feed\tCumulative Spindle\tDaily Machine/Cycle\tDaily Feed\tDaily Spindle\tSource\n';reportRows().forEach(({x,m})=>s+=`${x.date}\t${m.name}\t${m.type}\t${m.type==='haas'?x.cumulative.cycle:x.cumulative.machine}\t${m.type==='haas'?x.cumulative.feed:''}\t${m.id===H5&&Number.isFinite(x.cumulative.spindle)?x.cumulative.spindle:''}\t${m.type==='haas'?x.daily.cycle:x.daily.machine}\t${m.type==='haas'?x.daily.feed:''}\t${m.id===H5&&Number.isFinite(x.daily.spindle)?x.daily.spindle:''}\t${x.source}\n`);dl('Machine-Track.xls',s,'application/vnd.ms-excel')}
})();
